---
- name: Configure new WSL instances for AWX management
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  gather_facts: true
  vars:
    # Users configuration
    awx_user: "daniv"

    # Sudoers configuration options
    sudoers_type: "full"  # Options: "full", "systemctl", "minimal"

    # Essential packages to install
    essential_packages:
      - curl
      - wget
      - git
      - vim
      - jq
      - openssl
      - htop
      - tree
      - unzip

  tasks:
    - name: Display target host information
      ansible.builtin.debug:
        msg: |
          Configuring host: {{ inventory_hostname }}
          Hostname: {{ ansible_hostname | default('unknown') }}
          OS: {{ ansible_distribution | default('unknown') }} {{ ansible_distribution_version | default('') }}
          SSH Port: {{ ansible_port | default('22') }}

    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      register: apt_update
      failed_when: false

    - name: Upgrade system packages
      ansible.builtin.apt:
        upgrade: safe
        autoremove: true
        autoclean: true
      register: apt_upgrade
      failed_when: false

    - name: Install essential packages
      ansible.builtin.apt:
        name: "{{ essential_packages }}"
        state: present
      register: package_install
      failed_when: false

    - name: Configure sudoers file
      ansible.builtin.template:
        src: sudoers.j2
        dest: "/etc/sudoers.d/{{ awx_user }}-{{ sudoers_type }}"
        mode: '0440'
        owner: root
        group: root
        validate: 'visudo -cf %s'
      register: sudoers_result

    - name: Test passwordless sudo access
      ansible.builtin.command: sudo -n whoami
      become: false
      register: sudo_test
      failed_when: false
      changed_when: false

    - name: Configure system timezone (community.general)
      community.general.timezone:
        name: America/New_York
      register: timezone_result
      failed_when: false

    - name: Set kernel parameters for system optimization (ansible.posix)
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: true
      loop:
        - { name: "vm.swappiness", value: "10" }
        - { name: "net.core.rmem_max", value: "16777216" }
        - { name: "net.core.wmem_max", value: "16777216" }
      register: sysctl_result
      failed_when: false

    - name: Verify SSH service is running
      ansible.builtin.systemd:
        name: ssh
        state: started
        enabled: true
      register: ssh_service

    - name: Get SSH service status
      ansible.builtin.command: systemctl status ssh --no-pager -l
      register: ssh_status
      changed_when: false
      failed_when: false

    - name: Verify SSH is listening on correct port
      ansible.builtin.command: "netstat -tlnp | grep :{{ ansible_port | default('22') }}"
      register: ssh_port_check
      changed_when: false
      failed_when: false

    - name: Create system info summary
      ansible.builtin.set_fact:
        system_summary:
          hostname: "{{ ansible_hostname | default('unknown') }}"
          distribution: "{{ ansible_distribution | default('unknown') }} {{ ansible_distribution_version | default('') }}"
          ssh_port: "{{ ansible_port | default('22') }}"
          ssh_service: "{{ ssh_service.state | default('unknown') }}"
          sudo_access: "{{ sudo_test.rc == 0 }}"
          packages_updated: "{{ package_install.changed | default(false) }}"
          sudoers_configured: "{{ sudoers_result.changed | default(false) }}"
          timezone_configured: "{{ timezone_result.changed | default(false) }}"
          sysctl_optimized: "{{ sysctl_result.changed | default(false) }}"
          ssh_key_managed: "{{ ssh_key_result.changed | default(false) }}"

    - name: Display configuration summary
      ansible.builtin.debug:
        msg: |
          [SUCCESS] Configuration Summary for {{ inventory_hostname }}:

          System: {{ system_summary.hostname }} ({{ system_summary.distribution }})
          SSH Port: {{ system_summary.ssh_port }}
          SSH Service: {{ system_summary.ssh_service }}
          Sudo Access: {{ system_summary.sudo_access }}
          Packages Updated: {{ system_summary.packages_updated }}
          Sudoers Configured: {{ system_summary.sudoers_configured }}
          Timezone Configured: {{ system_summary.timezone_configured }}
          Kernel Optimized: {{ system_summary.sysctl_optimized }}
          SSH Keys Managed: {{ system_summary.ssh_key_managed }}

          Status: Ready for AWX service management!

- name: Test service management capabilities
  hosts: ubuntuAWX,argo_cd_mgt
  become: true
  become_method: ansible.builtin.sudo
  gather_facts: false
  vars:
    test_service: "cron"

  tasks:
    - name: Test service management - Get current status
      ansible.builtin.systemd:
        name: "{{ test_service }}"
      register: initial_status
      failed_when: false

    - name: Test service management - Stop service
      ansible.builtin.systemd:
        name: "{{ test_service }}"
        state: stopped
      register: stop_result
      failed_when: false

    - name: Test service management - Start service
      ansible.builtin.systemd:
        name: "{{ test_service }}"
        state: started
      register: start_result
      failed_when: false

    - name: Test service management - Verify final status
      ansible.builtin.systemd:
        name: "{{ test_service }}"
      register: final_status
      failed_when: false

    - name: Display service management test results
      ansible.builtin.debug:
        msg: |
          Service Management Test Results Service Management Test Results for {{ inventory_hostname }}:

          Service: {{ test_service }}
          Initial State: {{ initial_status.status.ActiveState | default('unknown') }}
          Stop Operation: {{ 'SUCCESS' if stop_result.changed else 'FAILED' }}
          Start Operation: {{ 'SUCCESS' if start_result.changed else 'FAILED' }}
          Final State: {{ final_status.status.ActiveState | default('unknown') }}

          Result: {{ 'PASS [SUCCESS]' if (final_status.status.ActiveState == 'active') else 'FAIL FAIL' }}
