---
- name: Stop services on WSL instances
  hosts: all
  become: true
  become_method: sudo
  become_user: daniv
  tasks:
    - name: Debug - Show basic info
      debug:
        msg: "Host: {{ inventory_hostname }}\nUser: {{ ansible_user }}\nService: {{ service_name }}"

    - name: Test sudo access
      command: whoami
      register: whoami_result

    - name: Show whoami result
      debug:
        msg: "Running as: {{ whoami_result.stdout }}"

    - name: Check service status before stop
      command: systemctl status {{ service_name }}
      register: status_before
      ignore_errors: true

    - name: Show service status before stop
      debug:
        msg: "Service status before: {{ status_before.stdout_lines[0] if status_before.stdout_lines else 'Service not found' }}"

    - name: Stop service using systemctl command
      command: systemctl stop {{ service_name }}
      register: stop_result
      ignore_errors: true

    - name: Show stop result
      debug:
        msg: "Stop result: {{ stop_result.stdout if stop_result.stdout else 'No output' }}, RC: {{ stop_result.rc }}"

    - name: Check service status after stop
      command: systemctl status {{ service_name }}
      register: status_after
      ignore_errors: true

    - name: Show final status
      debug:
        msg: "Final status: {{ status_after.stdout_lines[0] if status_after.stdout_lines else 'Service not found' }}"

    - name: Test additional services (if service_name is ssh)
      block:
        - name: Stop cron service
          command: systemctl stop cron
          register: cron_result
          ignore_errors: true

        - name: Stop systemd-resolved service
          command: systemctl stop systemd-resolved
          register: resolved_result
          ignore_errors: true

        - name: Show additional service results
          debug:
            msg: "Cron stop: {{ cron_result.rc }}, Resolved stop: {{ resolved_result.rc }}"
      when: service_name == "ssh"
