---
- name: Service lifecycle management on target hosts
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: "Stop {{ target_service | default('cron') }} service"
      include_role:
        name: service_management
      vars:
        service_name: "{{ target_service | default('cron') }}"
        service_action: "stop"

    - name: "Pause {{ wait_time | default(10) }} seconds"
      wait_for:
        timeout: "{{ wait_time | default(10) }}"

    - name: "Start {{ target_service | default('cron') }} service"
      include_role:
        name: service_management
      vars:
        service_name: "{{ target_service | default('cron') }}"
        service_action: "start"

    - name: "Verify {{ target_service | default('cron') }} service status"
      include_role:
        name: service_management
      vars:
        service_name: "{{ target_service | default('cron') }}"
        service_action: "status"
