---
- name: Test service stop/start cycle on WSL instances
  hosts: all
  become: true
  become_method: sudo
  roles:
    - service_management
  vars:
    service_name: "{{ target_service | default('cron') }}"
    service_action: "stop"
    debug_mode: true

- name: Wait 10 seconds
  hosts: all
  tasks:
    - wait_for:
        timeout: 10

- name: Start service
  hosts: all
  become: true
  become_method: sudo
  roles:
    - service_management
  vars:
    service_name: "{{ target_service | default('cron') }}"
    service_action: "start"
    debug_mode: true

- name: Verify service is running
  hosts: all
  become: true
  become_method: sudo
  roles:
    - service_management
  vars:
    service_name: "{{ target_service | default('cron') }}"
    service_action: "status"
    debug_mode: true
