---
all:
  children:
    wsl_instances:
      hosts:
        argo_cd_mgt:
          ansible_host: 172.22.192.129
          ansible_port: 2226
          ansible_user: daniv
        ubuntuAWX:
          ansible_host: 172.22.192.129
          ansible_port: 2225
          ansible_user: daniv
        wslkali1:
          ansible_host: 172.22.192.129
          ansible_port: 2224
          ansible_user: daniv
        wslubuntu1:
          ansible_host: 172.22.192.129
          ansible_port: 2223
          ansible_user: daniv
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        ansible_python_interpreter: /usr/bin/python3
        awx_user: daniv
        sudoers_type: "systemctl"
        
    service_test_hosts:
      hosts:
        argo_cd_mgt:
        ubuntuAWX:
        wslkali1:
        wslubuntu1:
      vars:
        service_mgmt_service_name: cron
        service_mgmt_service_state: stopped
