# SPDX-License-Identifier: MIT-0
---
- name: restart service
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: restarted
  register: restart_result

- name: Show service output
  ansible.builtin.debug:
    msg: "{{ restart_result }}"
