---
# Service Management Role - Ultra Clean Production
# Single task execution - no skipping messages

- name: "{{ service_action | title }} {{ service_name }} service"
  systemd:
    name: "{{ service_name }}"
    state: "{{ service_states[service_action] | default(omit) }}"
    enabled: "{{ service_enabled[service_action] | default(omit) }}"
  vars:
    service_states:
      stop: stopped
      start: started
      restart: restarted
    service_enabled:
      enable: yes
      disable: no
  when: service_action in ['stop', 'start', 'restart', 'enable', 'disable']

- name: "Check {{ service_name }} service status"
  command: "systemctl status {{ service_name }}"
  register: service_status
  changed_when: false
  failed_when: false
  when: service_action == "status"

- name: "Display service status"
  debug:
    msg: "{{ service_status.stdout_lines[0] | default('Service not found') }}"
  when: service_action == "status" and service_status is defined