---
# Service Management Role - Absolute Zero Noise
# Single task handles ALL actions

- name: "{{ service_action | title }} {{ service_name }} service"
  block:
    - name: "Service operation: {{ service_action }}"
      systemd:
        name: "{{ service_name }}"
        state: "{{ service_states[service_action] | default(omit) }}"
        enabled: "{{ service_enabled[service_action] | default(omit) }}"
      vars:
        service_states:
          stop: stopped
          start: started
          restart: restarted
        service_enabled:
          enable: yes
          disable: no
      when: service_action != "status"

    - name: "Service status check"
      command: "systemctl status {{ service_name }} --no-pager -l"
      register: service_status
      changed_when: false
      failed_when: false
      when: service_action == "status"