---
# Service Management Role - Zero Noise Production
# Single task handles all actions

- name: "{{ service_action | title }} {{ service_name }} service"
  systemd:
    name: "{{ service_name }}"
    state: "{{ service_states[service_action] | default(omit) }}"
    enabled: "{{ service_enabled[service_action] | default(omit) }}"
  vars:
    service_states:
      stop: stopped
      start: started
      restart: restarted
    service_enabled:
      enable: yes
      disable: no
  when: service_action != "status"

- name: "Check {{ service_name }} service status"
  command: "systemctl status {{ service_name }} --no-pager -l"
  register: service_status
  changed_when: false
  failed_when: false
  when: service_action == "status"