---
# Service Management Role - Production Ready
# Streamlined role for service lifecycle management

- name: "{{ service_action | title }} service: {{ service_name }}"
  systemd:
    name: "{{ service_name }}"
    state: "{{ service_states[service_action] }}"
  register: service_result
  when: service_action in ['stop', 'start', 'restart']
  vars:
    service_states:
      stop: stopped
      start: started  
      restart: restarted

- name: "Get {{ service_name }} service status"
  command: "systemctl status {{ service_name }}"
  register: service_status
  changed_when: false
  failed_when: false
  when: service_action == "status"

- name: "Set service status fact"
  set_fact:
    service_status_output: "{{ service_status.stdout_lines[0] | default('Service not found') }}"
  when: service_action == "status"

- name: "Enable {{ service_name }} service"
  systemd:
    name: "{{ service_name }}"
    enabled: yes
  register: service_result
  when: service_action == "enable"

- name: "Disable {{ service_name }} service"
  systemd:
    name: "{{ service_name }}"
    enabled: no
  register: service_result
  when: service_action == "disable"