---
- name: Restart service
  command: systemctl restart {{ service_name }}
  register: restart_result
  ignore_errors: true

- name: Show restart result
  debug:
    msg: "Restart result: {{ restart_result.stdout if restart_result.stdout else 'No output' }}, RC: {{ restart_result.rc }}"
  when: debug_mode | default(false)
