# SPDX-License-Identifier: MIT-0
---
- name: Stop service if started
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: "{{ service_state }}"
  register: service_mgmt_stop_result

- name: Show service result summary (clean)
  ansible.builtin.debug:
    msg: |
      Service: {{ service_name }}
      Action: {{ service_state }}
      Changed: {{ service_mgmt_stop_result.changed | ternary('YES', 'NO') }}
      Current State: {{ service_mgmt_stop_result.status.ActiveState }}
      Sub State: {{ service_mgmt_stop_result.status.SubState }}
  when: not debug_extra

- name: Show service result (verbose)
  ansible.builtin.debug:
    msg: "{{ service_mgmt_stop_result }}"
  when: debug_extra
