# SPDX-License-Identifier: MIT-0
---
- name: Stop service if started
  ansible.builtin.service:
    name: "{{ service_mgmt_service_name }}"
    state: "{{ service_mgmt_service_state }}"
  register: service_mgmt_stop_result

- name: Show service output
  ansible.builtin.debug:
    msg: "{{ service_mgmt_stop_result }}"
