---
galaxy_info:
  author: daniv
  description: A simple role to gather and display system information
  company: Personal Learning
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Kali
      versions:
        - rolling
  galaxy_tags:
    - system
    - information
    - reporting

dependencies: []
