---
galaxy_info:
  author: dan_iverson
  description: Flexible service management role for systemctl operations
  company: Personal
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Kali
      versions:
        - rolling
  galaxy_tags:
    - systemd
    - services
    - systemctl
    - management

dependencies: []