# Service Management Playbook for WSL Instances
---
- name: Manage services on WSL instances
  hosts: service_test_hosts
  become: true
  become_method: ansible.builtin.sudo
  gather_facts: true
  
  vars:
    # Override role defaults
    service_mgmt_service_name: "{{ service_name | default('cron') }}"
    service_mgmt_service_state: "{{ service_state | default('stopped') }}"
    service_mgmt_debug_extra: false
   
  roles:
    - role: dji_ansible.dji_administration.service_mgmt
