# Service Management Playbook for WSL Instances
---
- name: Manage services on WSL instances
  hosts: all_servers
  become: true
  become_method: ansible.builtin.sudo
  gather_facts: true
  
  roles:
    - role: dji_ansible.dji_administration.service_mgmt
      vars:
        service_name: "sshd"
        service_state: "started"
    
    - role: dji_ansible.dji_administration.service_mgmt
      vars:
        service_name: "cron"
        service_state: "stopped"
    
    - role: dji_ansible.dji_administration.service_mgmt
      vars:
        service_name: "apache2"
        service_state: "restarted"
