---
name: Ansible Lint

on:
  pull_request:
    branches: [main]
    paths:
      - '**/*.yml'
      - '**/*.yaml'
      - '.ansible-lint'
  push:
    branches: [main]
    paths:
      - '**/*.yml'
      - '**/*.yaml'
      - '.ansible-lint'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible Lint
        run: |
          pip install --upgrade pip
          pip install ansible-lint

      - name: Run Ansible Lint
        run: |
          echo "Ansible Lint version:"
          ansible-lint --version
          echo "Running Ansible Lint on playbooks..."
          ansible-lint . --exclude docs/ --exclude .github/ -v
